---
# Package management tasks specific to Debian
- name: Check if snapd is installed (unlikely on pure Debian)
  ansible.builtin.command: dpkg -l snapd
  register: package_management_snapd_check
  changed_when: false
  failed_when: false

- name: Remove snapd if present (rare on Debian)
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: true
    autoremove: true
  become: true
  when: package_management_snapd_check.rc == 0

- name: Debian package management tasks
  ansible.builtin.debug:
    msg: "Debian package management: snapd removal completed (if present)"
