---
- name: Linux Workstation Setup
  hosts: all
  become: true
  environment:
    http_proxy: http://192.168.68.127:3128
    https_proxy: http://192.168.68.127:3128
  vars_files:
    - vars/common_packages.yml
    - "vars/{{ ansible_os_family | lower }}.yml"

  pre_tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        my_user: >-
          {{ lookup('env', 'SUDO_USER') if lookup('env', 'SUDO_USER') else
           lookup('env', 'USER') if lookup('env', 'USER') != 'root' else
           ansible_user }}
    - name: Print out user info
      ansible.builtin.debug:
        msg: "my_user: {{ my_user }}"

    - name: Disk usage at start
      ansible.builtin.command: df -h /
      register: disk_start
      changed_when: false
    - name: Show disk usage at start
      ansible.builtin.debug:
        msg: "{{ disk_start.stdout_lines }}"

    - name: Update apt cache (Ubuntu/Debian)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install python-apt (Ubuntu/Debian)
      ansible.builtin.apt:
        name: python3-apt
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Update pacman cache (Archlinux)
      community.general.pacman:
        update_cache: true
      when: ansible_os_family == 'Archlinux'

  tasks:
    - name: Install distro specific packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ distro_packages }}"

    - name: Install common packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ common_distro_packages }}"

    - name: Include Docker installation tasks (Debian/Ubuntu)
      ansible.builtin.include_tasks: tasks/docker_install_main_ubuntu.yml
      when: ansible_os_family == 'Debian'

    - name: Desnappification (Ubuntu)
      ansible.builtin.include_tasks: tasks/desnap_ubuntu.yml
      when: ansible_os_family == 'Debian'

    - name: Flatpak installation
      ansible.builtin.include_tasks: tasks/install_flatpaks.yml

  post_tasks:
    - name: Disk usage at end
      ansible.builtin.command: df -h /
      register: disk_end
      changed_when: false
    - name: Show disk usage at end
      ansible.builtin.debug:
        msg: "{{ disk_end.stdout_lines }}"

  roles:
    - base
