---
- name: Linux Workstation Setup
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  
  vars_files:
    - vars/main.yml
    - "vars/{{ ansible_os_family | lower }}.yml"
  
  pre_tasks:
    - name: Update package cache
      include_tasks: "tasks/{{ ansible_os_family | lower }}/update-cache.yml"
  
  roles:
    - base
    - desktop