---
- name: Linux Workstation Setup
  hosts: all
  become: true
  environment:
    http_proxy: http://192.168.68.127:3128
    https_proxy: http://192.168.68.127:3128
  gather_facts: true

  vars_files:
    - vars/common_packages.yml
    - vars/common_flatpaks.yml

  pre_tasks:
    - name: Include pre-tasks
      ansible.builtin.include_tasks: pre_tasks/main.yml

  tasks: []

  roles:
    - containerization
    - package_management
    - dotfiles
    - desktop

  post_tasks:
    - name: Disk usage at end
      ansible.builtin.command: df -h /
      register: disk_end
      changed_when: false
    - name: Show disk usage at end
      ansible.builtin.debug:
        msg: "{{ disk_end.stdout_lines }}"
