---
- name: Linux Workstation Setup
  hosts: all
  #connection: local
  become: yes
  #gather_facts: yes
  
  vars_files:
    - vars/common_packages.yml
    - "vars/{{ ansible_os_family | lower }}.yml"

  pre_tasks:
    - name: Update apt cache (Ubuntu/Debian)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install python-apt (Ubuntu/Debian)
      ansible.builtin.apt:
        name: python3-apt
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Update pacman cache (Archlinux)
      ansible.builtin.pacman:
        update_cache: yes
      when: ansible_os_family == 'Archlinux'

  tasks:  
  - name: install distro specific packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: "{{ distro_packages }}"

  - name: install common packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: "{{ common_distro_packages }}"

  roles:
    - base