---
- name: Linux Workstation Setup
  hosts: all
  become: true
  environment:
    http_proxy: http://192.168.68.127:3128
    https_proxy: http://192.168.68.127:3128
  vars_files:
    - vars/common_packages.yml
    - "vars/{{ ansible_os_family | lower }}.yml"
    - vars/common_flatpaks.yml
  pre_tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        my_user: >-
          {{ lookup('env', 'SUDO_USER') if lookup('env', 'SUDO_USER') else
           lookup('env', 'USER') if lookup('env', 'USER') != 'root' else
           ansible_user }}
    - name: Print out user info
      ansible.builtin.debug:
        msg: "my_user: {{ my_user }}"

  roles:
    - desktop
