---
# GNOME Extensions installation (focusing on 2 essential ones)
- name: Create extensions directory
  ansible.builtin.file:
    path: "/home/{{ my_user }}/.local/share/gnome-shell/extensions"
    state: directory
    mode: '0755'
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  become: true

- name: Download Fullscreen Avoider extension
  ansible.builtin.get_url:
    url: https://extensions.gnome.org/extension-data/fullscreen-avoidernoobsai.github.com.v5.shell-extension.zip
    dest: "/tmp/fullscreen-avoider.zip"
    mode: '0644'
  become: false

- name: Create Fullscreen Avoider extension directory
  ansible.builtin.file:
    path: "/home/{{ my_user }}/.local/share/gnome-shell/extensions/fullscreen-avoider@noobsai.github.com"
    state: directory
    mode: '0755'
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  become: true

- name: Extract Fullscreen Avoider extension
  ansible.builtin.unarchive:
    src: "/tmp/fullscreen-avoider.zip"
    dest: "/home/{{ my_user }}/.local/share/gnome-shell/extensions/fullscreen-avoider@noobsai.github.com"
    creates: "/home/{{ my_user }}/.local/share/gnome-shell/extensions/fullscreen-avoider@noobsai.github.com/metadata.json"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    remote_src: true
  become: true

- name: Clean up extension zip files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/rounded-window-corners.zip"
    - "/tmp/fullscreen-avoider.zip"
  become: false
