---
# Main entry point for desktop role
- name: Include distro-specific GNOME installation
  ansible.builtin.include_tasks: "{{ distro_name }}.yml"

- name: Show GNOME installation status
  ansible.builtin.debug:
    msg: >-
      {%- if desktop_gnome_check.rc == 0 -%}
        GNOME is already installed, skipping installation
      {%- else -%}
        GNOME installation completed
      {%- endif -%}

- name: Install fonts
  ansible.builtin.include_tasks: fonts.yml

- name: Install and configure themes
  ansible.builtin.include_tasks: themes.yml

- name: Install GNOME extensions
  ansible.builtin.include_tasks: extensions.yml

- name: Apply GNOME configuration
  ansible.builtin.include_tasks: configuration.yml
