---
# Theme installation and setup
- name: Create themes directory
  ansible.builtin.file:
    path: "/home/{{ my_user }}/.themes"
    state: directory
    mode: '0755'
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  become: true

- name: Create icons directory
  ansible.builtin.file:
    path: "/home/{{ my_user }}/.icons"
    state: directory
    mode: '0755'
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  become: true

- name: Clone WhiteSur theme
  ansible.builtin.git:
    repo: https://github.com/vinceliuice/WhiteSur-gtk-theme.git
    dest: "/home/{{ my_user }}/.local/src/WhiteSur-gtk-theme"
    version: master
    force: true
  become: true
  become_user: "{{ my_user }}"
  register: desktop_whitesur_clone

- name: Install WhiteSur theme  # noqa no-handler
  ansible.builtin.command: ./install.sh -c Dark -t orange -N glassy
  args:
    chdir: "/home/{{ my_user }}/.local/src/WhiteSur-gtk-theme"
  become: true
  become_user: "{{ my_user }}"
  when: desktop_whitesur_clone is changed
  changed_when: true

- name: Install WhiteSur shell theme  # noqa no-handler
  ansible.builtin.command: ./tweaks.sh -g -o normal
  args:
    chdir: "/home/{{ my_user }}/.local/src/WhiteSur-gtk-theme"
  become: true
  become_user: "{{ my_user }}"
  when: desktop_whitesur_clone is changed
  changed_when: true

- name: Clone Nordzy icon theme
  ansible.builtin.git:
    repo: https://github.com/alvatip/Nordzy-icon.git
    dest: "/home/{{ my_user }}/.local/src/Nordzy-icon"
    version: master
    force: true
  become: true
  become_user: "{{ my_user }}"
  register: desktop_nordzy_clone

- name: Install Nordzy icon theme  # noqa no-handler
  ansible.builtin.command: ./install.sh -t dark -c light
  args:
    chdir: "/home/{{ my_user }}/.local/src/Nordzy-icon"
  become: true
  become_user: "{{ my_user }}"
  when: desktop_nordzy_clone is changed
  changed_when: true

- name: Clone Sunity cursor theme
  ansible.builtin.git:
    repo: https://github.com/alvatip/Sunity-cursors
    dest: "/home/{{ my_user }}/.local/src/Sunity-cursors"
    version: master
    force: true
  become: true
  become_user: "{{ my_user }}"
  register: desktop_sunity_clone

- name: Install Sunity cursor theme  # noqa no-handler
  ansible.builtin.command: ./install.sh
  args:
    chdir: "/home/{{ my_user }}/.local/src/Sunity-cursors"
  become: true
  become_user: "{{ my_user }}"
  when: desktop_sunity_clone is changed
  changed_when: true
