---
# Theme installation and setup
- name: Create themes directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.themes"
    state: directory
    mode: '0755'
  become: false

- name: Create icons directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.icons"
    state: directory
    mode: '0755'
  become: false

- name: Clone WhiteSur theme
  ansible.builtin.git:
    repo: https://github.com/vinceliuice/WhiteSur-gtk-theme.git
    dest: "{{ ansible_env.HOME }}/.local/src/WhiteSur-gtk-theme"
    version: master
    force: true
  become: false
  register: desktop_whitesur_clone

- name: Install WhiteSur theme  # noqa no-handler
  ansible.builtin.command: ./install.sh -c Dark -t orange -N glassy
  args:
    chdir: "{{ ansible_env.HOME }}/.local/src/WhiteSur-gtk-theme"
  become: false
  when: desktop_whitesur_clone is changed
  changed_when: true

- name: Install WhiteSur shell theme  # noqa no-handler
  ansible.builtin.command: ./tweaks.sh -g -o normal
  args:
    chdir: "{{ ansible_env.HOME }}/.local/src/WhiteSur-gtk-theme"
  become: false
  when: desktop_whitesur_clone is changed
  changed_when: true

- name: Clone Nordzy icon theme
  ansible.builtin.git:
    repo: https://github.com/alvatip/Nordzy-icon.git
    dest: "{{ ansible_env.HOME }}/.local/src/Nordzy-icon"
    version: master
    force: true
  become: false
  register: desktop_nordzy_clone

- name: Install Nordzy icon theme  # noqa no-handler
  ansible.builtin.command: ./install.sh -t dark -c light
  args:
    chdir: "{{ ansible_env.HOME }}/.local/src/Nordzy-icon"
  become: false
  when: desktop_nordzy_clone is changed
  changed_when: true

- name: Clone Sunity cursor theme
  ansible.builtin.git:
    repo: https://github.com/alvatip/Sunity-cursors
    dest: "{{ ansible_env.HOME }}/.local/src/Sunity-cursors"
    version: master
    force: true
  become: false
  register: desktop_sunity_clone

- name: Install Sunity cursor theme  # noqa no-handler
  ansible.builtin.command: ./install.sh
  args:
    chdir: "{{ ansible_env.HOME }}/.local/src/Sunity-cursors"
  become: false
  when: desktop_sunity_clone is changed
  changed_when: true
