---
- name: Configure Docker log rotation
  hosts: all
  become: true
  tasks:
    - name: Ensure /etc/docker directory exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure log rotation in /etc/docker/daemon.json
      ansible.builtin.copy:
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
      notify: restart docker

  handlers:
    - name: restart docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
