---
- name: Create Docker GPG keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

# Note the Jinja2 mapping for architecture as docker requires the debian style architecture name 'amd64' but Ansible provides 'x86_64'. Both names mean the same to humans. The arm stuff is not tested though.
- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ {'x86_64':'amd64','aarch64':'arm64','armv7l':'armhf'}
      [ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Verify Docker installation by running hello-world
  ansible.builtin.command: docker run hello-world
  register: docker_hello_world_result
  changed_when: docker_hello_world_result.rc != 0
  ignore_errors: yes