---
# Docker installation for Arch Linux/CachyOS
- name: Install Docker packages
  community.general.pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: present
  become: true

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Verify Docker installation by running hello-world
  ansible.builtin.command: docker run hello-world
  register: containerization_docker_hello_world_result
  changed_when: containerization_docker_hello_world_result.rc != 0
  failed_when: false
  become: true
