---
# Docker installation for Ubuntu and Ubuntu-based distros (Pop!_OS, Linux Mint, etc.)
# Following https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
- name: Create Docker GPG keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

# Note: The GPG key needs to go into .asc not .gpg
- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
  become: true

# Note: The Jinja2 mapping for architecture as docker requires the debian style architecture name 'amd64' but Ansible provides 'x86_64'
# Both names mean the same to humans. The arm stuff is not tested though
# Note: You need to include the 'signed-by' option, contrary to all the instructions I found online
- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ {'x86_64': 'amd64', 'aarch64': 'arm64', 'armv7l': 'armhf'}[ansible_architecture] }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true
  become: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: Verify Docker installation by running hello-world
  ansible.builtin.command: docker run hello-world
  register: containerization_docker_hello_world_result
  changed_when: containerization_docker_hello_world_result.rc != 0
  failed_when: false
  become: true
